version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - target: 5432
        published: 5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  hasura:
    image: hasura/graphql-engine:latest.cli-migrations-v3
    command: sh -c 'rm -rf /tmp/log/stdout.log && mkfifo /tmp/log/stdout.log && /bin/graphql-engine serve | tee /tmp/log/stdout.log'
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    volumes:
      - logs:/tmp/log
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: test
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup,query-log,http-log,webhook-log,websocket-log
      HASURA_GRAPHQL_LOG_LEVEL: info

  hasura-metric-adapter:
    build:
      context: ./
      dockerfile: Dockerfile
    image: hasura-metric-adapter:dev
    ports:
      - "9090:9090"
    depends_on:
      - "hasura"
    volumes:
      - logs:/tmp/log
    environment:
      LOG_FILE: /tmp/log/stdout.log
      HASURA_GRAPHQL_ADMIN_SECRET: test
      HASURA_GRAPHQL_ENDPOINT: "http://hasura:8080"
      EXCLUDE_COLLECTORS: "cron-triggers;event-triggers;scheduled-events"

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9000:9090
    volumes:
      - ./example/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./example/grafana/provisioning:/etc/grafana/provisioning
      - ./example/grafana/dashboards:/dashboards
volumes:
  db_data:
  logs:
  prometheus-data:
